In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
goldPrice = pd.read_csv('./dataset/Gold 1979-2021.csv')

In [3]:
goldPrice.head()

,Date,United States(USD),Europe(EUR),Japan(JPY),United Kingdom(GBP),Canada(CAD),Switzerland(CHF),India(INR),China(CNY),Turkey(TRY),Saudi Arabia(SAR),Indonesia(IDR),United Arab Emirates(AED),Thailand(THB),Vietnam(VND),Egypt(EGP),South Korean(KRW),Australia(AUD),South Africa(ZAR)
0,31-01-1979,233.7,144.8,45160.3,117.4,267.1,379.3,1840.8,NaN,NaN,745.2,139739.3,856.1,4511.3,NaN,NaN,108235.8,197.2,194.5
1,28-02-1979,251.3,154.6,50209.1,124.2,295.5,413.6,2011.7,NaN,NaN,827.8,154683.1,946.6,4985.7,NaN,NaN,119929.3,219.6,209.4
2,30-03-1979,240.1,148.0,50274.3,116.2,278.2,406.2,1940.2,NaN,NaN,796.7,148844.2,910.4,4812.9,NaN,NaN,116123.6,214.6,202.4
3,30-04-1979,245.3,152.8,54144.6,118.8,278.5,420.0,2013.1,NaN,NaN,819.4,152453.6,930.2,4891.0,NaN,NaN,117423.3,221.1,206.9
4,31-05-1979,274.6,172.0,61057.1,132.7,321.6,478.0,2253.4,NaN,NaN,933.3,171656.1,1048.4,5560.8,NaN,NaN,133889.6,250.7,233.7

In [4]:
goldPrice.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 511 entries, 0 to 510
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       511 non-null    object
 1   United States(USD)         511 non-null    float64
 2   Europe(EUR)                511 non-null    float64
 3   Japan(JPY)                 511 non-null    float64
 4   United Kingdom(GBP)        511 non-null    float64
 5   Canada(CAD)                511 non-null    float64
 6   Switzerland(CHF)           511 non-null    float64
 7   India(INR)                 511 non-null    float64
 8   China(CNY)                 439 non-null    float64
 9   Turkey(TRY)                464 non-null    float64
 10  Saudi Arabia(SAR)          511 non-null    float64
 11  Indonesia(IDR)             511 non-null    float64
 12  United Arab Emirates(AED)  511 non-null    float64
 13  Thailand(THB)              511 non-null    float64
 14  Vietnam(VND)               380 non-null    float64
 15  Egypt(EGP)                 392 non-null    float64
 16  South Korean(KRW)          511 non-null    float64
 17  Australia(AUD)             511 non-null    float64
 18  South Africa(ZAR)          511 non-null    float64
dtypes: float64(18), object(1)
memory usage: 76.0+ KB

## GoldPrice Managing

ใน GoldPrice ใช้ column - Date, Price(USD), Price(THB)

1. แปลงวันที่ของ Date เป็น 1 ทั้งหมด

In [5]:
goldPrice['Date'] = pd.to_datetime(goldPrice['Date'])
goldPrice['Date'] = goldPrice['Date'].dt.to_period('M').dt.to_timestamp()

C:\Users\User\AppData\Local\Temp\ipykernel_23492\2704216254.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  goldPrice['Date'] = pd.to_datetime(goldPrice['Date'])

In [6]:
goldPrice.head()

,Date,United States(USD),Europe(EUR),Japan(JPY),United Kingdom(GBP),Canada(CAD),Switzerland(CHF),India(INR),China(CNY),Turkey(TRY),Saudi Arabia(SAR),Indonesia(IDR),United Arab Emirates(AED),Thailand(THB),Vietnam(VND),Egypt(EGP),South Korean(KRW),Australia(AUD),South Africa(ZAR)
0,1979-01-01,233.7,144.8,45160.3,117.4,267.1,379.3,1840.8,NaN,NaN,745.2,139739.3,856.1,4511.3,NaN,NaN,108235.8,197.2,194.5
1,1979-02-01,251.3,154.6,50209.1,124.2,295.5,413.6,2011.7,NaN,NaN,827.8,154683.1,946.6,4985.7,NaN,NaN,119929.3,219.6,209.4
2,1979-03-01,240.1,148.0,50274.3,116.2,278.2,406.2,1940.2,NaN,NaN,796.7,148844.2,910.4,4812.9,NaN,NaN,116123.6,214.6,202.4
3,1979-04-01,245.3,152.8,54144.6,118.8,278.5,420.0,2013.1,NaN,NaN,819.4,152453.6,930.2,4891.0,NaN,NaN,117423.3,221.1,206.9
4,1979-05-01,274.6,172.0,61057.1,132.7,321.6,478.0,2253.4,NaN,NaN,933.3,171656.1,1048.4,5560.8,NaN,NaN,133889.6,250.7,233.7

2. สร้าง DataFrame เก็บข้อมูลเฉพาะที่ต้องการ
- ในที่นี้จะใช้ Date, Price(USD), Price(THB)

In [7]:
newGoldPrice = goldPrice[['Date','United States(USD)','Thailand(THB)']]
newGoldPrice.rename(columns={'United States(USD)': 'Price(USD)', 'Thailand(THB)': 'Price(THB)'}, inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_23492\1040682081.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newGoldPrice.rename(columns={'United States(USD)': 'Price(USD)', 'Thailand(THB)': 'Price(THB)'}, inplace=True)

In [8]:
newGoldPrice.head()

        Date  Price(USD)  Price(THB)
0 1979-01-01       233.7      4511.3
1 1979-02-01       251.3      4985.7
2 1979-03-01       240.1      4812.9
3 1979-04-01       245.3      4891.0
4 1979-05-01       274.6      5560.8

3. Export CSV

In [9]:
newGoldPrice.to_csv('./dataset/cleaned_GoldPrice.csv', index=False)