0. Import Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

0. Import Datasets

In [2]:
dayEvents = pd.read_csv('./dataset/World Important Dates.csv')
goldPrice = pd.read_csv('./dataset/Gold 1979-2021.csv')

In [3]:
dayEvents.head()

,Sl. No,Name of Incident,Date,Month,Year,Country,Type of Event,Place Name,Impact,Affected Population,Important Person/Group Responsible,Outcome
0,1,Indus Valley Civilization Flourishes,Unknown,Unknown,2600 BC,India,Civilization,Indus Valley,Development of one of the world's earliest urb...,Local inhabitants,Indus Valley people,Positive
1,2,Battle of the Ten Kings,Unknown,Unknown,1400 BC,India,Battle,Punjab,Rigvedic tribes consolidated their control ove...,Rigvedic tribes,Sudas,Positive
2,6,Establishment of the Delhi Sultanate,Unknown,Unknown,1206,India,Political,Delhi,Muslim rule established in parts of India,People of Delhi and surrounding regions,QutbUnknownudUnknowndin Aibak,Mixed
3,7,Battle of Panipat,21,April,1526,India,Battle,Panipat,Foundation of the Mughal Empire in India,Northern Indian kingdoms,Babur,Mixed
4,8,Establishment of British Raj,1,May,1858,India,Colonial,Whole India,Start of direct British governance in India,Indian subcontinent,British East India Company/Empire,Negative

In [4]:
goldPrice.head()

,Date,United States(USD),Europe(EUR),Japan(JPY),United Kingdom(GBP),Canada(CAD),Switzerland(CHF),India(INR),China(CNY),Turkey(TRY),Saudi Arabia(SAR),Indonesia(IDR),United Arab Emirates(AED),Thailand(THB),Vietnam(VND),Egypt(EGP),South Korean(KRW),Australia(AUD),South Africa(ZAR)
0,31-01-1979,233.7,144.8,45160.3,117.4,267.1,379.3,1840.8,NaN,NaN,745.2,139739.3,856.1,4511.3,NaN,NaN,108235.8,197.2,194.5
1,28-02-1979,251.3,154.6,50209.1,124.2,295.5,413.6,2011.7,NaN,NaN,827.8,154683.1,946.6,4985.7,NaN,NaN,119929.3,219.6,209.4
2,30-03-1979,240.1,148.0,50274.3,116.2,278.2,406.2,1940.2,NaN,NaN,796.7,148844.2,910.4,4812.9,NaN,NaN,116123.6,214.6,202.4
3,30-04-1979,245.3,152.8,54144.6,118.8,278.5,420.0,2013.1,NaN,NaN,819.4,152453.6,930.2,4891.0,NaN,NaN,117423.3,221.1,206.9
4,31-05-1979,274.6,172.0,61057.1,132.7,321.6,478.0,2253.4,NaN,NaN,933.3,171656.1,1048.4,5560.8,NaN,NaN,133889.6,250.7,233.7

## DayEvents Managing

1. แปลง Month และ Year ใน dayEvents

In [5]:
def formatYear(x):
    if 'BC' in x:
        return int(x.replace(' BC', '')) * -1
    return int(x)

In [6]:
dayEvents['Year'] = dayEvents['Year'].apply(formatYear)

In [7]:
dayEvents['Month'].unique()

array(['Unknown', 'April', 'May', 'August', 'December', 'November',
       'June', 'October', 'February', 'July', 'January', 'March',
       'September'], dtype=object)

In [8]:
monthMap = {
    'January': 1,
    'February': 2,
    'March': 3,
    'April': 4,
    'May': 5,
    'June': 6,
    'July': 7,
    'August': 8,
    'September': 9,
    'October': 10,
    'November': 11,
    'December': 12
}

def formatMonth(x):
    if x in monthMap:
        return int(monthMap[x])
    else:
        return np.nan

In [9]:
dayEvents['Month'] = dayEvents['Month'].apply(formatMonth).astype('Int64', errors='ignore')

In [10]:
dayEvents.head()

,Sl. No,Name of Incident,Date,Month,Year,Country,Type of Event,Place Name,Impact,Affected Population,Important Person/Group Responsible,Outcome
0,1,Indus Valley Civilization Flourishes,Unknown,<NA>,-2600,India,Civilization,Indus Valley,Development of one of the world's earliest urb...,Local inhabitants,Indus Valley people,Positive
1,2,Battle of the Ten Kings,Unknown,<NA>,-1400,India,Battle,Punjab,Rigvedic tribes consolidated their control ove...,Rigvedic tribes,Sudas,Positive
2,6,Establishment of the Delhi Sultanate,Unknown,<NA>,1206,India,Political,Delhi,Muslim rule established in parts of India,People of Delhi and surrounding regions,QutbUnknownudUnknowndin Aibak,Mixed
3,7,Battle of Panipat,21,4,1526,India,Battle,Panipat,Foundation of the Mughal Empire in India,Northern Indian kingdoms,Babur,Mixed
4,8,Establishment of British Raj,1,5,1858,India,Colonial,Whole India,Start of direct British governance in India,Indian subcontinent,British East India Company/Empire,Negative

ใน GoldPrice ใช้ column - Date, Price(USD), Price(THB)

In [11]:
goldPrice.head()

,Date,United States(USD),Europe(EUR),Japan(JPY),United Kingdom(GBP),Canada(CAD),Switzerland(CHF),India(INR),China(CNY),Turkey(TRY),Saudi Arabia(SAR),Indonesia(IDR),United Arab Emirates(AED),Thailand(THB),Vietnam(VND),Egypt(EGP),South Korean(KRW),Australia(AUD),South Africa(ZAR)
0,31-01-1979,233.7,144.8,45160.3,117.4,267.1,379.3,1840.8,NaN,NaN,745.2,139739.3,856.1,4511.3,NaN,NaN,108235.8,197.2,194.5
1,28-02-1979,251.3,154.6,50209.1,124.2,295.5,413.6,2011.7,NaN,NaN,827.8,154683.1,946.6,4985.7,NaN,NaN,119929.3,219.6,209.4
2,30-03-1979,240.1,148.0,50274.3,116.2,278.2,406.2,1940.2,NaN,NaN,796.7,148844.2,910.4,4812.9,NaN,NaN,116123.6,214.6,202.4
3,30-04-1979,245.3,152.8,54144.6,118.8,278.5,420.0,2013.1,NaN,NaN,819.4,152453.6,930.2,4891.0,NaN,NaN,117423.3,221.1,206.9
4,31-05-1979,274.6,172.0,61057.1,132.7,321.6,478.0,2253.4,NaN,NaN,933.3,171656.1,1048.4,5560.8,NaN,NaN,133889.6,250.7,233.7

1. แยกส่วนของ Date เก็บแยกไว้ของ GoldPrice

In [ ]:
goldPrice['Date'] = pd.to_datetime(goldPrice['Date'], format='%d-%m-%Y')

# แยกเป็น 3 ส่วน
goldPrice['Day'] = goldPrice['Date'].dt.day
goldPrice['Month'] = goldPrice['Date'].dt.month
goldPrice['Year'] = goldPrice['Date'].dt.year

In [13]:
goldPrice.head()

,Date,United States(USD),Europe(EUR),Japan(JPY),United Kingdom(GBP),Canada(CAD),Switzerland(CHF),India(INR),China(CNY),Turkey(TRY),...,United Arab Emirates(AED),Thailand(THB),Vietnam(VND),Egypt(EGP),South Korean(KRW),Australia(AUD),South Africa(ZAR),Day,Month,Year
0,1979-01-31,233.7,144.8,45160.3,117.4,267.1,379.3,1840.8,NaN,NaN,...,856.1,4511.3,NaN,NaN,108235.8,197.2,194.5,31,1,1979
1,1979-02-28,251.3,154.6,50209.1,124.2,295.5,413.6,2011.7,NaN,NaN,...,946.6,4985.7,NaN,NaN,119929.3,219.6,209.4,28,2,1979
2,1979-03-30,240.1,148.0,50274.3,116.2,278.2,406.2,1940.2,NaN,NaN,...,910.4,4812.9,NaN,NaN,116123.6,214.6,202.4,30,3,1979
3,1979-04-30,245.3,152.8,54144.6,118.8,278.5,420.0,2013.1,NaN,NaN,...,930.2,4891.0,NaN,NaN,117423.3,221.1,206.9,30,4,1979
4,1979-05-31,274.6,172.0,61057.1,132.7,321.6,478.0,2253.4,NaN,NaN,...,1048.4,5560.8,NaN,NaN,133889.6,250.7,233.7,31,5,1979

2. สร้าง DataFrame เก็บข้อมูลเฉพาะที่ต้องการ
- ในที่นี้จะใช้ Day, Month, Year, Price(USD), Price(THB)

In [15]:
goldPrice.columns

Index(['Date', 'United States(USD)', 'Europe(EUR)', 'Japan(JPY)',
       'United Kingdom(GBP)', 'Canada(CAD)', 'Switzerland(CHF)', 'India(INR)',
       'China(CNY)', 'Turkey(TRY)', 'Saudi Arabia(SAR)', 'Indonesia(IDR)',
       'United Arab Emirates(AED)', 'Thailand(THB)', 'Vietnam(VND)',
       'Egypt(EGP)', 'South Korean(KRW)', 'Australia(AUD)',
       'South Africa(ZAR)', 'Day', 'Month', 'Year'],
      dtype='object')

In [16]:
newGoldPrice = goldPrice[['Day','Month','Year','United States(USD)','Thailand(THB)']]
newGoldPrice.rename(columns={'United States(USD)': 'Price(USD)', 'Thailand(THB)': 'Price(THB)'})

     Day  Month  Year  Price(USD)  Price(THB)
0     31      1  1979       233.7      4511.3
1     28      2  1979       251.3      4985.7
2     30      3  1979       240.1      4812.9
3     30      4  1979       245.3      4891.0
4     31      5  1979       274.6      5560.8
..   ...    ...   ...         ...         ...
506   31      3  2021      1691.1     52845.3
507   30      4  2021      1767.7     55040.2
508   31      5  2021      1900.0     59344.9
509   30      6  2021      1763.2     56509.0
510   30      7  2021      1825.8     60007.8

[511 rows x 5 columns]