0. Import Libraries

In [80]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

0. Import Datasets

In [81]:
dayEvents = pd.read_csv('./dataset/cleaned_dayEvents.csv')
goldPrice = pd.read_csv('./dataset/cleaned_GoldPrice.csv')

In [82]:
dayEvents.head()

,Unnamed: 0,Sl. No,Name of Incident,Date,Month,Year,Country,Type of Event,Place Name,Impact,Affected Population,Important Person/Group Responsible,Outcome
0,7,11,PokhranUnknownII Nuclear Tests,11,5,1998,India,Nuclear Test,Pokhran,India declared itself a nuclear state,International community,Atal Bihari Vajpayee,Mixed
1,8,12,Mumbai Terror Attacks,26,11,2008,India,Terrorism,Mumbai,Highlighted the threat of international terrorism,Citizens of Mumbai,LashkarUnknowneUnknownTaiba,Negative
2,14,18,Operation Blue Star,1,6,1984,India,Military Operation,Amritsar,Removal of armed militants from Golden Temple ...,Sikh community,"Indian Government, Sikh militants",Negative
3,15,19,Kargil War,Unknown,5,1999,India,Military Conflict,"Kargil, Ladakh",India regained control of Kargil; heightened p...,Indian Armed Forces,"Indian Government, Pakistani Military",Positive
4,16,20,Right to Information Act Enacted,15,6,2005,India,Legislation,India,Empowered citizens to seek information from pu...,Indian citizens,Government of India,Positive

In [83]:
goldPrice.head()

   Unnamed: 0        Date  Day  Month  Year  Price(USD)  Price(THB)
0           0  1979-01-31   31      1  1979       233.7      4511.3
1           1  1979-02-28   28      2  1979       251.3      4985.7
2           2  1979-03-30   30      3  1979       240.1      4812.9
3           3  1979-04-30   30      4  1979       245.3      4891.0
4           4  1979-05-31   31      5  1979       274.6      5560.8